---

- name: check for variables
  when: >
    (vars[item] is not defined) or
    ( vars[item] is defined and not vars[item] ) or
    ( vars[item] is defined and vars[item]|length == 0 )
  with_items: "{{ duo_unix_required }}"
  ansible.builtin.fail:
    msg: >
      Required variables not defined or empty.

# - name: retrieving duo security gpg key
#   ansible.builtin.rpm_key: state=present key=https://duo.com/DUO-GPG-PUBLIC-KEY.asc

- name: add duo repository
  ansible.builtin.template:
    src: templates/duosecurity.repo.j2
    dest: "/etc/yum.repos.d/duosecurity.repo"
    mode: 0644
    owner: root
    group: root

- name: install packages
  ansible.builtin.package:
    name: ["ca-certificates", "duo_unix", "openssh-server"]
    state: present

- name: set duo configuration
  ansible.builtin.template: src=templates/pam_duo.conf.j2 dest=/etc/duo/pam_duo.conf owner=root group=root mode=0600
  notify:
    - sshd restart

- name: update pam.d configuration
  ansible.builtin.template: src=templates/sshd.j2 dest=/etc/pam.d/sshd owner=root group=root mode=0644
  notify:
    - sshd restart

# - debug: msg="trigger sshd restart"
#   notify:
#     - sshd restart
#   changed_when: true
#   when: (not duo_unix_role_debug|bool)
