---
prerun: false
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint .
platforms:
  - name: instance
    image: ghcr.io/escapace/ansible-test-containers
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
