---
prerun: false
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: instance
    image: ghcr.io/escapace/ansible-test-containers
    pre_build_image: true
provisioner:
  name: ansible
